global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api_monitoring'
    static_configs:
      - targets: ['api1:5000']
        labels:
          api_name: 'api1'
      - targets: ['api2:5001']
        labels:
          api_name: 'api2'
